version: "3.9"
services:
  next-app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT
      - NEXTAUTH_URL
      - NEXTAUTH_SECRET
      - GOOGLE_CLIENT_ID
      - GOOGLE_CLIENT_SECRET
      - NEXT_PUBLIC_API_HOST
      - NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY
    ports:
      - "${PORT}:${PORT}"
