import Sidebar from "./components/Sidebar";
import "./styles.css";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div>
      <Sidebar
        dashboard="/dashboard"
        products="/my-shop/products"
        orders="/my-shop/orders"
        messages="/messages"
        profile="/profile"
        history="/history"
        reviews="/reviews"
        settings="/settings"
        profileImg="/product.png"
        name="Tylor Swift"
        email="tylor@gmail.com"
      />
      <div className="md:ml-64 z-30">
        <main>{children}</main>
      </div>
    </div>
  );
}
