import "./globals.css";
import type { Metadata } from "next";
import Providers from "@/redux/provider";
import AuthProvider from "./context/auth";

export const metadata: Metadata = {
  title: "Unirent",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="main ">
        <AuthProvider>
          <Providers>{children}</Providers>
        </AuthProvider>
      </body>
    </html>
  );
}
