import Sidebar from "./components/Sidebar";
import "./styles.css";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div>
      <Sidebar
        dashboard="/profile/dashboard"
        product="/profile/my-shop/products"
        orders="/profile/my-shop/orders"
        message="/profile/message/0"
        history="/profile/history"
        reviews="/profile/reviews"
        settings="/profile/settings"
        profileImg="/product.png"
        name="Tylor Swift"
        email="tylor@gmail.com"
      ></Sidebar>
      <div className="md:ml-64 z-30">
        <main>{children}</main>
      </div>
    </div>
  );
}
