name: Deploy to Self-Hosted

on:
  workflow_run:
    workflows: [Build and Test]
    branches: ["main"]
    types:
      - completed

env:
  PORT: ${{ secrets.PORT }}
  API_URL: ${{ secrets.API_URL }}
  NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
  NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
  GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
  GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
  NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: ${{ secrets.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY }}

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to Self-Hosted and Clean up
        run: |
          docker compose up -d --build
      - name: Clean up Docker Images
        run: |
          docker system prune -af